### PR TITLE
Update create-process-on-windows.yml mapping to ATT&CK T1106

### PR DESCRIPTION
**Pull request by erhlee-bird**
Just adding the att&ck category for T1106 to the create-process-on-windows.yml rule.
I think this makes sense for the Windows rule.

https://attack.mitre.org/techniques/T1106/

### CODE REVIEW

**Comment by mr-tz** [comment]
Hm, interesting. The way I read this is that we could assign this category to every rule using a Windows API call?
So I am not sure if this is really helpful.

**Comment by mr-tz** [comment]
Hm, I'm still not convinced here.
https://attack.mitre.org/tactics/TA0002/ describes Execution as "The adversary is trying to run malicious code."
That also applies to potentially all rules we have.

**Comment by erhlee-bird** [comment]
Cool, totally understand. Thank you for taking the time to consider and review.

**Comment by mr-tz** [comment]
Of course, please keep ideas, suggestions, and feedback coming!

**Pull request closed without merging**
