### PR TITLE
sha* rules and updates

### PR DESCRIPTION
**Pull request by williballenthin**
ref #632

https://github.com/mandiant/capa-testfiles/pull/151

### CODE REVIEW

**Comment by williballenthin** [comment]
(awaiting CI linter)

**Comment by mr-tz** [comment]
looks like you broke the linter :)

**Comment by williballenthin** [comment]
image

**Comment by williballenthin** [comment]
rule parsing improved in https://github.com/mandiant/capa/pull/1283/

**Comment by williballenthin** [comment]
missing space

image

**Comment by williballenthin** [comment]
image

**Review by mr-tz — APPROVED** [review]

**Pull request merged**
