### PR TITLE
Create enumerate-minifilter-drivers.yml

### PR DESCRIPTION
**Pull request by jaxxpnd**
Moved rule to enumerate minifilter drivers from anti-analysis/anti-av to host-interaction/filter, added sample to test samples repository

### CODE REVIEW

**Comment by mr-tz** [comment]
does this supersede #775?

**Comment by jaxxpnd** [comment]
yes

**Comment by mr-tz** [comment]
Ok, please close the other PR then. I still don't see the test file. Can you link your PR?

**Comment by jaxxpnd** [comment]
Closed #775. Sorry, here is the test file:
https://github.com/mandiant/capa-testfiles/pull/180

**Review by williballenthin — APPROVED** [review]
lgtm

**Pull request merged**
