### PR TITLE
Create read-from-mailslot.yml

### PR DESCRIPTION
**Pull request by crowface28**

### CODE REVIEW

**Review by williballenthin — APPROVED** [review]
logic looks good. lets see what CI says

**Comment by crowface28** [comment]
Looks like it failed for no sample provided.  Because reasons, I can't supply that.  Possible to skip?

**Comment by williballenthin** [comment]
could we use VT to find an alternative sample? Otherwise let's move the rule to the nursery until we can find a test case.

**Comment by williballenthin** [comment]
(for future reference, no need to provide references to non-public samples. feel free to update the PR to redact that if you'd like.)

**Comment by crowface28** [comment]
Removed example and moved to nursery.  Will work on compiling a sample we can use for linting

**Review by williballenthin — APPROVED** [review]
thank you!

**Pull request merged**
