### PR TITLE
Update HC-128 (variation used in Winnti malware)

### PR DESCRIPTION
**Pull request by TakahiroHaruyama**
Tested on a Winnti malware sample as the screenshot attached.
Screenshot 2024-07-25 at 12 36 49

### CODE REVIEW

**Review by mr-tz — COMMENTED** [review]
LGTM, thanks!
Can you sign the CLA, please?

**Comment by mr-tz** [comment]
@TakahiroHaruyama, can you look at the CLA, please? Otherwise I'm afraid we have to close this.

**Comment by TakahiroHaruyama** [comment]
Got 400 when updating the check. Not sure how to fix it.

**Comment by mr-tz** [comment]
Got it, thank you!

**Pull request merged**
